title: Aloveu || Archives
author: 김광훈
author_birthday: 1983년 12월 16일
author_bio: Hi :D
author_email: "kyouyoum@gmail.com"
author_location: 경기도 하남시

urls:
  - name: Archives
    url: /
  - name: Profile
    url: /profile
  - name: Tags
    url: /tags

# pagination of posts
paginate: 7
per_page: 10
paginate_path: "/page/:num/"

excerpt_separator: <!--more-->

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
