title: Aloveu || Archives
author_logo: profile.png
author: 김광훈( 金光勳 , Kim GwangHun )
author_birthday: 1983년 12월 16일
author_bio: Hi :D
author_email: "kyouyoum@gmail.com"
author_location: 경기도 하남시

urls:
  - name: Home
    url: /
  - name: About
    url: /about.html
  - name: Blog
    url: /blog.html

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page:num/"

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
